import { auth } from "@/auth";
import { inter } from "@/constants/font";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
import "@/public/styles/main.scss";
import Sidebar from "@/components/shared/dashboard/Sidebar";
import Topbar from "@/components/shared/dashboard/Topbar";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await auth();
    return (
        <SessionProvider session={session}>
            <html lang="en">
                <head>
                    <link
                        rel="apple-touch-icon"
                        sizes="180x180"
                        href="assets/icons/apple-touch-icon.png"
                    />
                    <link
                        rel="icon"
                        type="image/png"
                        sizes="32x32"
                        href="assets/icons//favicon-32x32.png"
                    />
                    <link
                        rel="icon"
                        type="image/png"
                        sizes="16x16"
                        href="assets/icons//favicon-16x16.png"
                    />
                    <link rel="manifest" href="assets/icons/site.webmanifest" />
                    <link
                        rel="mask-icon"
                        href="assets/icons/safari-pinned-tab.svg"
                        color="#5bbad5"
                    />
                    <meta name="msapplication-TileColor" content="#da532c" />
                    <meta name="theme-color" content="#ffffff" />
                </head>
                <body className={`${inter.className}`}>
                    <Topbar />

                    <main className="flex flex-row">
                        <Sidebar />
                        <section className="flex min-h-screen flex-1 flex-col items-center bg-dark-1 px-6 pb-10 pt-28 max-md:pb-32 sm:px-10">
                            <div className="w-full">{children}</div>
                        </section>
                    </main>
                    <Toaster
                        position="top-center"
                        toastOptions={{
                            style: { background: "#0f0f0f", color: "#fff" },
                            success: {
                                duration: 3000,
                            },
                            error: {
                                duration: 5000,
                            },
                        }}
                    />
                </body>
            </html>
        </SessionProvider>
    );
}
