import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await auth();
    return (
        <SessionProvider session={session}>
            <html lang="en">
                <body>{children}</body>
            </html>
        </SessionProvider>
    );
}

